version: '3.8'

services:
  php:
    image: php:8.0-fpm
    container_name: php_container
    volumes:
      - ./src:/var/www/html
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y mariadb-client &&
        docker-php-entrypoint php-fpm
      "
    depends_on:
      - db

  composer:
    image: composer:latest
    container_name: composer_container
    volumes:
      - ./src:/app
    working_dir: /app
    command: composer install
    depends_on:
      - php

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php

  db:
    image: mariadb:latest
    container_name: mariadb_container
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

volumes:
  db_data:
